---
- name: Install mysql packages
  apt: pkg={{ item }} state=present
  with_items:
   - mysql-server-5.5
   - python-mysqldb  # for ansible mysql modules
  register: install_mysql_action

- name: Make server accept mysql connections on all hosts
  lineinfile: dest=/etc/mysql/my.cnf regexp="^[\s]*bind-address[\s]*=" line="bind-address = ::"
  register: change_mysql_conf_action

- name: Restart mysqld service
  service: name=mysql state=restarted
  when: change_mysql_conf_action.changed

- name: Create database user
  mysql_user: name={{ db_user }} password={{ db_password }} priv=*.*:ALL host={{ item }} state=present
  with_items:
    - '%'
    - 'localhost'
  sudo: no
  when: install_mysql_action.changed

- name: Remove anonymous database user
  mysql_user: name='' host={{ item }} state=absent login_user={{ db_user }} login_password={{ db_password }}
  with_items:
    - 'localhost'  # maybe not only "localhost"
  sudo: no
  when: install_mysql_action.changed

- name: Remove the test database
  mysql_db: name=test state=absent login_user={{ db_user }} login_password={{ db_password }}
  when: install_mysql_action.changed