---
- name: Deploy Tiny Blog Demo dev
  hosts: box
  user: '{{ remote_user }}'  # Built-in variable "ansible_ssh_user" will be changed to the local user in "local_action", so a user defined variable is used instead.
  sudo: yes

  roles:
    - common
    - mysql
    - mongodb
    - redis
    - nginx
    - php-fpm
    - webapp