---
- name: Remove the line "AcceptEnv" in sshd_config
  lineinfile: dest=/etc/ssh/sshd_config regexp="^[\s]*AcceptEnv[\s]+" state=absent
  notify: restart sshd

- name: Change apt source to cn.archive.ubuntu.com
  copy: src=sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644

- name: Update apt cache
  apt: update_cache=yes

- name: Install prerequisite packages
  apt: pkg={{ item }} state=present
  with_items:
    - python-pycurl
    - rsync
    - unzip
    - subversion  # for installing some packages in Composer

- name: Create remote_project_dir
  file: path={{ remote_project_dir }} state=directory
  sudo: no