---
- name: Add MongoDB repository apt key
  apt_key: url=http://docs.mongodb.org/10gen-gpg-key.asc state=present

- name: Add MongoDB repository  # official ubuntu packages 
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present update_cache=yes

- name: Install MongoDB
  apt: pkg=mongodb-10gen state=present