---
- name: Remove the line "AcceptEnv" in sshd_config
  lineinfile: dest=/etc/ssh/sshd_config regexp="^AcceptEnv" state=absent
  notify: restart sshd
  when: box

- name: Change apt source to ftp.cn.debian.org
  copy: src=sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644
  when: box

- name: Update apt cache
  apt: update_cache=yes

- name: Install python-apt
  apt: pkg=python-apt state=present

- name: Install python-pycurl
  apt: pkg=python-pycurl state=present

- name: Install rsync
  apt: pkg=rsync state=present
  when: state == "dev"

- name: Create app dir
  command: mkdir -p {{ remote_srv_dir }}