---
- name: Keep ssh key files not accessible by others  # prevent warning
  local_action: command chmod 0600 {{ private_key_path }}
  sudo: no

- name: Remove the line "AcceptEnv" in sshd_config
  lineinfile: dest=/etc/ssh/sshd_config regexp="^[\s]*AcceptEnv[\s]+" state=absent
  notify: restart sshd

- name: Change apt source to ftp.cn.debian.org
  copy: src=sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644

- name: Update apt cache
  apt: update_cache=yes

- name: Install python-apt
  apt: pkg=python-apt state=present

- name: Install python-pycurl
  apt: pkg=python-pycurl state=present

- name: Install rsync
  apt: pkg=rsync state=present

- name: Create remote_www_dir
  command: mkdir -p {{ remote_www_dir }}
  sudo: no