---
- name: Copy webapp source files to server
  local_action: command rsync -aI --rsh="ssh -p {{ ansible_ssh_port }} -i {{ private_key_path }}" {{ local_src_dir }} {{ remote_user }}@{{ inventory_hostname }}:{{ remote_project_dir }}
  sudo: no

- name: Chmod 777 webapp runtime directory
  file: path={{ remote_runtime_dir }} mode=0777
  sudo: no

- name: Install php modules
  apt: pkg={{ item }} state=present
  with_items:
    - php5-mysql
    - php5-imagick
    - php5-redis

- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php chdir={{ remote_project_dir }} creates=composer.phar

- name: Install Composer packages
  command: php composer.phar install chdir={{ remote_project_dir }}

- name: Create database
  mysql_db: login_user={{ db_user }} login_password={{ db_password }} name={{ db_name }} state=present
  sudo: no

- name: Initial database data with script file
  mysql_db: login_user={{ db_user }} login_password={{ db_password }} name={{ db_name }} state=import target={{ remote_sql_file }}
  sudo: no