---
- name: Install php-fpm
  apt: pkg={{ item }} state=present
  with_items:
    - php5
    - php5-fpm
  notify: restart php-fpm

- name: Install xdebug
  apt: pkg=php5-xdebug state=present

- name: Configure xdebug
  lineinfile: dest=/etc/php5/fpm/conf.d/xdebug.ini line={{ item }}
  with_items:
    - "xdebug.remote_enable=1"
    - "xdebug.remote_connect_back=1"
  notify: restart php-fpm