---
- name: Add nginx repository apt key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Add nginx repository  # official ubuntu precise packages 
  apt_repository: repo='{{ item }}' state=present update_cache=yes
  with_items:
    - 'deb http://nginx.org/packages/ubuntu/ precise nginx'
    - 'deb-src http://nginx.org/packages/ubuntu/ precise nginx'

- name: Install nginx
  apt: pkg=nginx state=present

- name: Remove nginx default configuration files
  shell: rm -f /etc/nginx/conf.d/* removes=/etc/nginx/conf.d/

- name: Copy nginx configuration for webapp
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=0644
  notify: restart nginx

# tweaked upstart script, but they can't work properly