---
- name: Install nginx
  apt: pkg=nginx state=present

- name: Remove nginx default configuration files
  shell: rm -f {{ item }}/* removes={{ item }}
  with_items:
    - /etc/nginx/sites-enabled
    - /etc/nginx/conf.d

- name: Copy nginx website configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx